name: Run Trading Bot

on:
  schedule:
    - cron: '7,22,37,52 * * * *' # اجرا در دقایق ۷، ۲۲، ۳۷ و ۵۲ هر ساعت (برای فرار از ترافیک و تاخیر)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install ccxt pandas numpy requests

      - name: Run Bot Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MANUAL_RUN: "false"
        run: |
          python bot.py
